server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cvc_db
    username: postgres
    password: "@Srinani7029"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
